baseURL = "https://zchen.im/"
languageCode = "zh-cn"
author = "Zhe Chen"
title = "Zhe Chen"
theme = "vanilla-bootstrap-hugo-theme"
disqusShortname = "chenzhekl"

[[taxonomies]]
tag = "tags"
category = "categories"

[[menu.nav]]
name = "Home"
pre = "home"
url = "/"
weight = 1

[[menu.nav]]
name = "About me"
pre = "smile"
url = "/about"
weight = 2

[params]
katex = true

[markup.goldmark.renderer]
unsafe= true
