baseURL = "https://chenzhekl.me/"
languageCode = "zh-cn"
author = "Zhe Chen"
title = "chenzhekl"
theme = "lithium"
googleAnalytics = "UA-33320605-1"
disqusShortname = "chenzhekl"

[[menu.main]]
name = "PRML 中文版"
weight = -1
url = "/prml/"
[[menu.main]]
name = "About me"
url = "/about/"

[params]
description = "PhD at Kyoto University"

highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdnjs.cloudflare.com/ajax/libs"
highlightjsTheme = "github"

MathJaxCDN = "https://cdnjs.cloudflare.com/ajax/libs"
MathJaxVersion = "2.7.1"

[params.logo]
url = "logo.png"
width = 50
height = 50
alt = "Logo"
