baseURL = "https://zchen.im/"
languageCode = "zh-cn"
author = "Zhe Chen"
title = "Zhe Chen"
theme = "typo"

[taxonomies]
tag = "tags"
category = "categories"

[params]
homeCollectionTitle = "Posts"
homeCollection = "posts"

theme = "auto"
colorPalette = "gruvebox"
hideHeader = false

homeIntroTitle = 'Hi!'
homeIntroContent = """
Hi, I am a Ph.D. student at Computer Vision Laboratory, Kyoto University.
I got my bachelor’s degree in electrical engineering from Zhejiang University in 2015.
My research interests are mainly in inverse rendering, computational photography, and machine learning.

Email: me at zchen dot im
"""

[[params.social]]
name = "github"
url = "https://github.com/chenzhekl"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/~zchen"

[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "About"
url = "/about"

[[params.menu]]
name = "Posts"
url = "/posts"

[markup]
[markup.highlight]
style = "algol"
