baseURL = "https://zchen.im/"
languageCode = "zh-cn"
author = "Zhe Chen"
title = "chenzhekl"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-33320605-1"
disqusShortname = "chenzhekl"

[[taxonomies]]
tag = "tags"
category = "categories"

[[menu.nav]]
name = "Home"
url = "/"
weight = 1

[[menu.nav]]
name = "Blog"
url = "/posts/"
weight = 2

[[menu.nav]]
name = "PRML 翻译"
url = "/prml/"
weight = 3

[[menu.nav]]
name = "About"
url = "/about/"
weight = 4

[params]
katex = true
homeText = "Hello!"
