baseURL = "https://zchen.im/"
languageCode = "zh-cn"
author = "Zhe Chen"
title = "Zhe Chen"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-33320605-1"
disqusShortname = "chenzhekl"

[[taxonomies]]
tag = "tags"
category = "categories"

[[menu.nav]]
name = "About"
url = "/"
weight = 1

[params]
katex = true
homeText = "Hello!"

[markup.goldmark.renderer]
unsafe= true
