baseURL = "https://chenzhekl.me/"
languageCode = "zh-cn"
author = "Zhe Chen"
title = "chenzhekl"
theme = "cocoa"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[params]
include_rss = true
author = "Zhe Chen"
selfintro = "PhD at Kyoto University | Computer Vision | Machine Learning"
email = "chenzhekl@gmail.com"
twitter = "//twitter.com/chenzhekl"
instagram = "//instagram.com/chenzhekl"
facebook = "//facebook.com/chenzhekl"
